### ISSUE TITLE
No response from home

### ISSUE THREAD

**Issue by corrpel** [JosephDuffy/homebridge-pc-volume#1]
Hi,
Thank you very much for this plugin.
Unfortunately, i was not able to use it.
All the alternative accesories are responding but this one not.
It says "No response" in IOS home app. The dependency is installed (loudness), i am using the soundcard as hw:0,0 and the mixer control name in alsamixer or amixer is 'Master'.
Maybe i am doing something wrong?! As accesory i've used "Computer"
Thanks!

**Comment by JosephDuffy** [comment]
Thanks for downloading the project! :D

It sounds like you're using Linux? Unfortunately I've not got a system to test it, but I was hoping it would work thanks to `node-loudness` :/ Looking at the source it should support so I think we're going to have to debug this further.

Can you [start homekit in debug mode](https://github.com/nfarina/homebridge/wiki/Basic-Trouble-Shooting) and then post the contents of `/var/log/homebridge.err` and `/var/log/homebridge.log` after trying to use it a couple of times?

Just to double check, can you also post the contents of `~/.homebridge/config.json`?

**Comment by corrpel** [comment]
Hi,
Yes using alsa.
It seemd that there are no homebridge files in /var/log.
I started the app in debug mode, here is the content:
The last two infos appear when i click on the widget in home app on IOS:

> (node:1615) DeprecationWarning: sys is deprecated. Use util instead.
>   EventedHTTPServer Server listening on port 51826 +0ms
> [3/8/2017, 8:52:26 AM] Homebridge is running on port 51826.
>   EventedHTTPServer [::ffff:192.168.1.105] New connection from client +1s
>   EventedHTTPServer [::ffff:192.168.1.105] HTTP server listening on port 34821 +6ms
>   EventedHTTPServer [::ffff:192.168.1.105] HTTP request: /pair-verify +22ms
>   HAPServer [CC:33:3D:E3:CE:30] HAP Request: POST /pair-verify +1ms
>   HAPServer [CC:33:3D:E3:CE:30] Pair verify step 1/2 +17ms
>   EventedHTTPServer [::ffff:192.168.1.105] HTTP Response is finished +53ms
>   EventedHTTPServer [::ffff:192.168.1.105] HTTP request: /pair-verify +113ms
>   HAPServer [CC:33:3D:E3:CE:30] HAP Request: POST /pair-verify +0ms
>   HAPServer [CC:33:3D:E3:CE:30] Pair verify step 2/2 +5ms
>   HAPServer [CC:33:3D:E3:CE:30] Client 327527BD-0FD8-424B-8F7D-7DB8AFCDFE3F verification complete +10ms
>   EventedHTTPServer [::ffff:192.168.1.105] HTTP Response is finished +3ms
>   EventedHTTPServer [::ffff:192.168.1.105] HTTP request: /accessories +10ms
>   HAPServer [CC:33:3D:E3:CE:30] HAP Request: GET /accessories +0ms
>   EventedHTTPServer [::ffff:192.168.1.105] HTTP Response is finished +10ms
>   EventedHTTPServer [::ffff:192.168.1.105] HTTP request: /characteristics +371ms
>   HAPServer [CC:33:3D:E3:CE:30] HAP Request: PUT /characteristics +0ms
>   Accessory [Homebridge] Processing characteristic set: [{"aid":2,"iid":12,"ev":true},{"aid":2,"iid":15,"ev":true},{"aid":3,"iid":11,"ev":true},{"aid":3,"iid":14,"ev":true},{"aid":4,"iid":11,"ev":true},{"aid":4,"iid":14,"ev":true},{"aid":5,"iid":11,"ev":true},{"aid":5,"iid":14,"ev":true},{"aid":6,"iid":12,"ev":true},{"aid":6,"iid":15,"ev":true}] +4ms
>   Accessory [Homebridge] Registering Characteristic "Reachable" for events +3ms
>   Accessory [Homebridge] Registering Characteristic "Category" for events +1ms
>   Accessory [Homebridge] Registering Characteristic "Reachable" for events +0ms
>   Accessory [Homebridge] Registering Characteristic "Category" for events +1ms
>   Accessory [Homebridge] Registering Characteristic "Reachable" for events +0ms
>   Accessory [Homebridge] Registering Characteristic "Category" for events +0ms
>   Accessory [Homebridge] Registering Characteristic "Reachable" for events +0ms
>   Accessory [Homebridge] Registering Characteristic "Category" for events +1ms
>   Accessory [Homebridge] Registering Characteristic "Reachable" for events +0ms
>   Accessory [Homebridge] Registering Characteristic "Category" for events +0ms
>   EventedHTTPServer [::ffff:192.168.1.105] HTTP Response is finished +3ms
>   EventedHTTPServer [::ffff:192.168.1.105] HTTP request: /characteristics +184ms
>   HAPServer [CC:33:3D:E3:CE:30] HAP Request: PUT /characteristics +0ms
>   Accessory [Homebridge] Processing characteristic set: [{"aid":2,"iid":9,"ev":true},{"aid":2,"iid":10,"ev":true}] +2ms
>   Accessory [Homebridge] Registering Characteristic "On" for events +1ms
>   Accessory [Homebridge] Registering Characteristic "Brightness" for events +0ms
>   EventedHTTPServer [::ffff:192.168.1.105] HTTP Response is finished +2ms
>   EventedHTTPServer [::ffff:192.168.1.105] HTTP request: /characteristics +14ms
>   HAPServer [CC:33:3D:E3:CE:30] HAP Request: PUT /characteristics +1ms
>   Accessory [Homebridge] Processing characteristic set: [{"aid":3,"iid":9,"ev":true}] +3ms
>   Accessory [Homebridge] Registering Characteristic "On" for events +0ms
>   EventedHTTPServer [::ffff:192.168.1.105] HTTP Response is finished +2ms
>   EventedHTTPServer [::ffff:192.168.1.105] HTTP request: /characteristics +71ms
>   HAPServer [CC:33:3D:E3:CE:30] HAP Request: PUT /characteristics +0ms
>   Accessory [Homebridge] Processing characteristic set: [{"aid":4,"iid":9,"ev":true}] +2ms
>   Accessory [Homebridge] Registering Characteristic "On" for events +0ms
>   EventedHTTPServer [::ffff:192.168.1.105] HTTP Response is finished +2ms
>   EventedHTTPServer [::ffff:192.168.1.105] HTTP request: /characteristics +173ms
>   HAPServer [CC:33:3D:E3:CE:30] HAP Request: PUT /characteristics +1ms
>   Accessory [Homebridge] Processing characteristic set: [{"aid":5,"iid":9,"ev":true}] +1ms
>   Accessory [Homebridge] Registering Characteristic "On" for events +1ms
>   EventedHTTPServer [::ffff:192.168.1.105] HTTP Response is finished +1ms
>   EventedHTTPServer [::ffff:192.168.1.105] HTTP request: /characteristics +296ms
>   HAPServer [CC:33:3D:E3:CE:30] HAP Request: PUT /characteristics +0ms
>   Accessory [Homebridge] Processing characteristic set: [{"aid":6,"iid":9,"ev":true},{"aid":6,"iid":10,"ev":true}] +1ms
>   Accessory [Homebridge] Registering Characteristic "On" for events +1ms
>   Accessory [Homebridge] Registering Characteristic "Brightness" for events +1ms
>   EventedHTTPServer [::ffff:192.168.1.105] HTTP Response is finished +1ms
>   EventedHTTPServer [::ffff:192.168.1.105] HTTP request: /characteristics?id=6.10,6.9 +4s
>   HAPServer [CC:33:3D:E3:CE:30] HAP Request: GET /characteristics?id=6.10,6.9 +1ms
>   Accessory [Homebridge] Getting value for Characteristic "Brightness" +9ms
>   Accessory [Homebridge] Getting value for Characteristic "On" +26ms
>   Accessory [Homebridge] Got Characteristic "Brightness" value: undefined +80ms
>   Accessory [Homebridge] Error getting value for Characteristic "Brightness": Alsa Mixer Error: failed to parse output +1ms
>   Accessory [Homebridge] Got Characteristic "On" value: undefined +5ms
>   Accessory [Homebridge] Error getting value for Characteristic "On": Alsa Mixer Error: failed to parse output +1ms
>   EventedHTTPServer [::ffff:192.168.1.105] HTTP Response is finished +3ms
>   EventedHTTPServer [::ffff:192.168.1.105] HTTP request: /characteristics?id=6.10,6.9 +6s
>   HAPServer [CC:33:3D:E3:CE:30] HAP Request: GET /characteristics?id=6.10,6.9 +1ms
>   Accessory [Homebridge] Getting value for Characteristic "Brightness" +2ms
>   Accessory [Homebridge] Getting value for Characteristic "On" +12ms
>   Accessory [Homebridge] Got Characteristic "Brightness" value: undefined +16ms
>   Accessory [Homebridge] Error getting value for Characteristic "Brightness": Alsa Mixer Error: failed to parse output +9ms
>   Accessory [Homebridge] Got Characteristic "On" value: undefined +9ms
>   Accessory [Homebridge] Error getting value for Characteristic "On": Alsa Mixer Error: failed to parse output +0ms
>   EventedHTTPServer [::ffff:192.168.1.105] HTTP Response is finished +2ms



My config file:

> {
>     "bridge": {
>         "name": "Homebridge",
>         "username": "CC:33:3D:E3:CE:30",
>         "port": 51826,
>         "pin": "011-45-154"
>     },
> 
> "accessories": [
>    {
>        "accessory": "mpd",
>        "name": "guerrilla",
>        "host": "localhost",
>        "port": "6600"
>    },
>     {
>               "accessory": "Script",
>               "name": "guerrilla",
>               "on": "/home/osmc/rem/radio.sh",
>               "off": "/home/osmc/rem/st.sh",
>               "state": "/usr/local/lib/node_modules/homebridge-script/state.sh",
>               "fileState": "/usr/local/lib/node_modules/homebridge-script/script.flag",
>               "on_value" : "true",
>               "exact_match": true
>               },
>     {
>               "accessory": "Script",
>               "name": "tv",
>               "on": "/home/osmc/rem/playk.sh",
>               "off": "/home/osmc/rem/pausek.sh",
>               "state": "/usr/local/lib/node_modules/homebridge-script/state.sh",
>               "fileState": "/usr/local/lib/node_modules/homebridge-script/script.flag",
>               "on_value" : "true",
>               "exact_match": true
>               },
>     {
>               "accessory": "Script",
>               "name": "bedtime",
>               "on": "/home/osmc/rem/st.sh",
>               "off": "/home/osmc/rem/sleeptime.sh",
>               "state": "/usr/local/lib/node_modules/homebridge-script/state.sh",
>               "fileState": "/usr/local/lib/node_modules/homebridge-script/script.flag",
>               "on_value" : "true",
>               "exact_match": true
>               },
> {
>       "accessory": "Computer",
>       "name": "MacBook"
>     }
> 
> ]
> }


Thank you very much for helping on this!

**Comment by JosephDuffy** [comment]
I've taken a look at the logs you've posted and the source code of `node-loudness` and I can't see anything obvious. I would recommend trying to recreate the issue using `node-loudness` directly, and if you can, opening an issue there and see if there's a possible fix. Also check out the [`node-loudness` repo](https://github.com/LinusU/node-loudness) and previous issues to see if any are similar to your issue/setup.

I'll leave this issue open for a couple of days in case any more information is discovered, but it is likely that this ticket will be closed.

**Comment by corrpel** [comment]
It's ok the errors are related to loudness.
Thank you very much for looking into it!

**Comment by JosephDuffy** [comment]
Let me know if you come up with a solution and I will add it to the README or try and implement the fix in this project/node-loudness. For now I'll close this issue :)
