### ISSUE TITLE
Instalation issues

### ISSUE THREAD

**Issue by dallasgroot** [JosephDuffy/homebridge-pc-volume#194]
Hey there, recently just installed Homebridge

I'm having issues with setting up my config json file, when copying the sample code you have into 

https://jsonformatter.curiousconcept.com/ I am left with issues 
Expecting object or array, not string. highlighted on Accessories

`"accessories":[
   {
      "accessory":"ComputerSpeakers",
      "name":"MacBook",
      "services":[
         "lightbulb"
      ]
   }
]`

Thank you for your time

**Comment by JosephDuffy** [comment]
Hey,

The example in README is intended to be a key in the `config.json` file. The [homebridge repo has an example](https://github.com/nfarina/homebridge/blob/master/config-sample.json). If you were to use the sample with homebridge-pc-volume if would be:

```
{
  "bridge": {
    "name": "Homebridge",
    "username": "CC:22:3D:E3:CE:30",
    "port": 51826,
    "pin": "031-45-154"
  },
  
  "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",
  "ports": {
    "start": 52100,
    "end": 52150,
    "comment": "This section is used to control the range of ports that separate accessory (like camera or television) should be bind to."
  },
"accessories": [
    {
      "accessory": "ComputerSpeakers",
      "name": "MacBook"
    }
  ],

  "platforms": [
    {
      "platform" : "PhilipsHue",
      "name" : "Hue"
    }
  ]
}

```

**Comment by dallasgroot** [comment]
Thanks for your reply, I figured it out after looking at other samples

**Comment by JosephDuffy** [comment]
Great :) I can see that the README isn't super clear so I'll update it
