### ISSUE TITLE
New Speaker Accessory in iOS 11

### ISSUE THREAD

**Issue by HarryChen55** [JosephDuffy/homebridge-pc-volume#4]
Hello

I've been using this plugin for quite some time, and it's very useful. Thank you very much for making this plugin.

Currently, speakers are disguised as light bulbs for Homekit to be able to control it. Because speakers aren't supported in Homekit.
But speakers are finally officially supported in iOS 11 now, and iOS 11 will be released on 17th this month. Do you have any plans to update this plugin to support iOS 11?

Thanks!

**Comment by JosephDuffy** [comment]
I've had plans to do this but I've been waiting for iOS 11 to be out. Since the GM is here I've downloaded it and will look in to doing this.

My only concern is backwards compatibility, so it might take a little time (e.g. how does iOS 10 handle it, for homes with a mixture of devices)

**Comment by JosephDuffy** [comment]
I have just tried this but it is still showing as "Not Supported" currently. [I have asked on a Homebridge issue](https://github.com/nfarina/homebridge/issues/1326#issuecomment-330060732) about this and will hopefully push an update in the future. There's a chance an iOS update will fix this too.

**Comment by JosephDuffy** [comment]
I've pushed out 1.1.0. It now "supports" speakers, but iOS 11 does not appear to. I have added the option to expose the volume as a fan, which has a lovely little spinning fan animation, and is currently what I'm using.

Sorry that it can't support speakers! Hopefully speaker support (outside of AirPlay 2) will come in a future iOS update :)
