### ISSUE TITLE
Control MacBook while HomeBridge running on Raspberry.

### ISSUE THREAD

**Issue by TommyCardello** [JosephDuffy/homebridge-pc-volume#6]
Thank you for your work with this plugin. It works very well.
I have a question.
The plugin can control volume only on a device where it runs.
It is impossible to control MacBook while Homebridge runs on Raspberry.
In this case, it controls Raspberry Volume.

Is it possible somehow to send volume setting to a specific IP/device/MacBook?

I use some Yamaha plugins and it's possible to control volume there. Is it possible to add this functionality?

**Comment by JosephDuffy** [comment]
As far as having the pi controlling your Mac's volume it's certainly possible, but not with homebridge and this plugin. I'm afraid that's too out of scope for this project!

One option (that I use) is to have a homebridge server running on the Mac and install this plugin on the Mac. Would this work for you?

**Comment by TommyCardello** [comment]
Yes, it works. 
I'm trying to automate everything, in this case I have to launch server on Mac manually each time I get home. That's why I've just got Raspberry Pi.

Thank you anyway. I appreciate it.
I was just curious asking that.

**Comment by JosephDuffy** [comment]
If you've not come across it check out pm2. Its what I use on my mac to have homebridge startup automatically.

**Comment by TommyCardello** [comment]
Wow, that was fast 👍 
Thanks!
I'll check it out. That might be an option for me.

I'm trying to build a fully remote system + automatization and remote access through the internet.
Mac might not work for me, as it's not always on. 

But I understand, that's out of scope for this project.

**Comment by JosephDuffy** [comment]
No problem!

You can have multiple homebridge instances running in the same house. When the mac is offline any HomeKit accessories will show as "Unavailable," which might help your situation a little.

**Comment by TommyCardello** [comment]
It makes sense. Thanks for this advise!

**Comment by JosephDuffy** [comment]
I hope you get the setup you want!

**Comment by Rhadadi** [comment]
Hi there,
I installed Homebridge on my mac and installed all plugins and updated configurations. Now I got raspberry pi amd installed and ran Homebridge on that too. It is just a new instance. How to migrate or merge these two instances?

**Comment by JosephDuffy** [comment]
@Rhadadi There shouldn't be anything you need to do to have this project work. If you want to control both the Mac and the Raspberry Pi you'll need to keep both instances running. If you want to have the same config and the Mac on the Pi you'll need to migrate Homebridge, e.g. by following the [Homebridge Backup and Restore guide](https://github.com/homebridge/homebridge/wiki/Backup-and-Restore).
