### ISSUE TITLE
Question: Can be used local, not remotely?

### ISSUE THREAD

**Issue by jeatrexs** [JosephDuffy/homebridge-pc-volume#606]
Hi,

sorry but i could not find any point in documentation, so I'm asking here:

Do I see this right, that this plugin is only for controlling the device on which it is installed including homebridge?
So there is no possibility controlling volume of a one or more PCs in my network, when running homebridge with this plugin on a raspberrypi ?

Thanks in advance.

**Comment by JosephDuffy** [comment]
That's right, it's only controlling the computer it's installed on.

You can install Homebridge and this plugin on as many computers as you want and they'll all appear in the same home in the Home app, with each Homebridge instance being a unique bridge.

I think you'd need to use different a unqiue "username" and "pin" in each of the Homebridge configs, but I've successfully controlled multiple computers in my house using this technique.

**Comment by jeatrexs** [comment]
Thanks that confirms my thoughts.

> I think you'd need to use different a unqiue "username" and "pin" in each of the Homebridge configs, but I've successfully controlled multiple computers in my house using this technique.

My thought was to have one raspberry pi as the one and only bridge / "homebridge" from which i can control everything in my home. I also got me a deConz (zigbee module) for my raspberry pi so now I could remove any other bridges like Philips Hue Bridge etc. so I only need the one raspberry pi for everything. I'm not sure, if I would like to install homebridge on my PCs at home. But if this is the only way to use this plugin, I will think about it. thank you!

**Comment by JosephDuffy** [comment]
Hopefully you find a solution that fits your needs :) There may be another project out there that enables remotely controlling the volume, which could then possibly be hooked up to Homebridge.

I'll close this for now but feel free to open again if you run in to any issues!
